name: End-to-end tests
on: [push]

jobs:
  cucumber-typescript:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run clean-build
      - run: npm run webdriver-update
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo apt install ./google-chrome-stable_current_amd64.deb -y
      - run: npm run test -- --headless
